Task1: Add CLI
leapfrogtechnology/lf-training pull request #3
Opened 2020-08-01 17:49 UTC by susankoju

![image (10)](https://user-images.githubusercontent.com/31833796/89107232-45fdfe80-d44f-11ea-87cd-8fe2827b52f6.jpg)

2020-08-05 07:33 UTC, sanjaymhj requested changes

2020-08-05 07:33 UTC, sanjaymhj commented on Python/susankoju/task1/store_result.py
> +    parser.add_argument('--subject', type=str, help='a name of subject')
Please confirm to requirement: There should me limited choice for subject

2020-08-05 16:55 UTC, susankoju commented on Python/susankoju/task1/store_result.py
> +    parser.add_argument('--subject', type=str, help='a name of subject')
Okay dai

2020-08-06 08:01 UTC, Basanta78 commented on Python/susankoju/task1/store_result.py
> +                            pass
raise or handle the expections

2020-08-06 08:01 UTC, Basanta78 commented on Python/susankoju/task1/store_result.py
> +        pass
.

2020-08-10 02:46 UTC, merged