task1
leapfrogtechnology/lf-training pull request #9
Opened 2020-08-02 06:15 UTC by palsonkansakar09

2020-08-05 07:35 UTC, sanjaymhj requested changes

2020-08-05 07:35 UTC, sanjaymhj commented on Python/PalsonKansakar/task1/task1_pt1.py
> +main()
Consider controlling code flow from https://docs.python.org/3/library/__main__.html

2020-08-06 06:37 UTC, sagarlf reviewed
Looks good. Just review the comments made. Will merge it.

2020-08-06 06:37 UTC, sagarlf commented on Python/PalsonKansakar/task1/task1_pt1.py
> +        print("Division by zero error")
this exception is just caught but not mitigated

2020-08-10 02:44 UTC, merged